name: phage_contig_annot
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - "python>=3.11"
  - "scipy>=1.9.3"
  - "seaborn>=0.12"
  - "trnascan-se=2.0.9"
  - trf

  - pip:
    - bcbio-gff
    - dna-features-viewer
    - psutil
    - requests
    - tqdm
    - biopython
    - numpy
    - pandas
    - matplotlib
    - "snakemake>=9.0"
    - "click>=8.0"
    - "pyrodigal-gv>=0.3"
    - "pyhmmer>=0.12"
    - "plotly>=6.0"
