[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "phage_contig_annotator"
version = "0.0.1"

[project.scripts]
phage_contig_annotator = "cli:main"

[options.packages.find]
where = src

[options.package_data]
config =
    *.ini
